### ISSUE TITLE
SSSP with different results

### ISSUE THREAD

**Issue by chenyi95** [thu-pacman/GeminiGraph#10]
I run SSSP with com-friendster dataset.
It seems weird that different results occur at 5th and 6th iteration.
I checked the results of other iteration which are exact with other tools.

This snapshot shows two trials but it happens every time. Is 5/6th iteration using some heuristic ways? Why?
![example](https://user-images.githubusercontent.com/28288387/41448255-339eda26-708c-11e8-9d8d-242fc4802ba8.png)

btw what is the meaning of distance[64037984]？ what is 64037984?

**Comment by coolerzxw** [comment]
Hi. This is possible since Gemini's executions are not deterministic, so for each run you may observe different intermediate states. However, the final results should be consistent if the algorithms are implemented correctly.
The current implementation of SSSP will print the largest distance reachable from the source vertex (well it seems that the largest distance in your example is 0 and you may check whether this is due to all the weights being 0).

**Comment by chenyi95** [comment]
In my case, the weight is 1 for all edges. The largest distance is 28 for this node, and the number of nodes at 28-hop is the exact.
Actually the number of other k-th hops are the same except 5-hop and 6-hop.

**Comment by coolerzxw** [comment]
Hi, the numbers after "active(...)>=" (well there is a typo here i.e. ">=" should be "<=") are the numbers of activations in these iterations so they are not exact numbers. I hope this can resolve your confusion.

**Comment by chenyi95** [comment]
I understand and close this issue
