### ISSUE TITLE
run distributed algorithms

### ISSUE THREAD

**Issue by chenyi95** [thu-pacman/GeminiGraph#2]
Hi
I try to run distributed algorithms on the cluster by the following input:
srun -N 8 ./toolkits/bfs /path/to/twitter-2010.binedgelist 41652230 20

but it seems each machine independently runs the algorithm by itself and the final outputs are the eight repeated results with the same runtime as the single machine. In my view, the distributed version should save running time.

So is there a way to run distributed algorithm as stated in the paper?

**Comment by coolerzxw** [comment]
Hi, @chenyi95  
I am afraid this is an issue of some mis-configuration. Can you run other MPI programs in a distributed way on your cluster?

**Comment by chenyi95** [comment]
Hi,@coolerzxw
The MPI works well for Powergraph on the cluster.
Also, I can run mpiexec -n 3  ./toolkits/bfs /path/to/twitter-2010.binedgelist 41652230 20  on the cluster, but again, this triggered paralleled computation on each machine.

So could you tell me the correct configuration if I missed.

**Comment by coolerzxw** [comment]
@chenyi95 I came across this situation before (i.e. each process of an MPI program oblivious of others) and the problem turned out to be a mis-match between the MPI library used for compilation and the MPI runtime of the cluster (e.g. different MPI implementations like OpenMPI used for compilation but MVAPICH2 used for execution, b.t.w I was told that different versions of a same MPI library leading to incompatible passing/parsing of environmental variables can also cause similar behaviors). You may check whether this is also your case.
